language: python
python:
  - "3.6"
services:
  - postgresql
env:
  global:
    - LEGISPRO_URL='http://example.com'
    - UNHABITAT_URL='http://example.com'
    - UNFAO_URL='http://example.com'
    - LEGISPRO_USER='test'
    - LEGISPRO_PASS='test'
    - ES_VERSION=5.4.1
    - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
    - ELASTICSEARCH_HOST=elastic:changeme@127.0.0.1:9200
before_install:
  - sudo apt-get install libpoppler-cpp-dev
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - pip install -r requirements-dev.txt
before_script:
  - sudo service elasticsearch start
  - psql -c 'create database test_lcc;' -U postgres
script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - coverage run --source='.' ./manage.py test --settings=lcctoolkit.settings.test
after_success: coveralls
notifications:
  email:
    recipients:
      - purepython@eaudeweb.ro
